/**
 * Declare
 */
declare const URL_BASE_API_HISTORIAL_NOTIFICACIONES_W: string;
declare const URL_BASE_API_REENVIO_NOTIFICACIONES_W: string;
declare const URL_BASE_API_NOTIFICACIONES_W: string;
declare const ENV: string;
declare const URL_BASE_API_MASTER_TYPELIST_W:string;


/**
 * Asignation
 */
const _URL_BASE_API_HISTORIAL_NOTIFICACIONES_W = URL_BASE_API_HISTORIAL_NOTIFICACIONES_W;
const _URL_BASE_API_REENVIO_NOTIFICACIONES_W = URL_BASE_API_REENVIO_NOTIFICACIONES_W;
const _URL_BASE_API_NOTIFICACIONES_W = URL_BASE_API_NOTIFICACIONES_W;
const _ENV = ENV;
const _URL_BASE_API_MASTER_TYPELIST_W = URL_BASE_API_MASTER_TYPELIST_W;


/**
 * Export
 */
export {_URL_BASE_API_HISTORIAL_NOTIFICACIONES_W as URL_BASE_API_HISTORIAL_NOTIFICACIONES_W};
export {_URL_BASE_API_REENVIO_NOTIFICACIONES_W as URL_BASE_API_REENVIO_NOTIFICACIONES_W};
export {_URL_BASE_API_NOTIFICACIONES_W as URL_BASE_API_NOTIFICACIONES_W};
export {_ENV as ENV};
export {_URL_BASE_API_MASTER_TYPELIST_W as URL_BASE_API_MASTER_TYPELIST_W};
