/**
 * Declare
 */
declare const URL_BASE_API_HISTORIAL_NOTIFICACIONES_W: string;
declare const URL_BASE_API_REENVIO_NOTIFICACIONES_W: string;
declare const URL_BASE_API_NOTIFICACIONES_W: string;
declare const ENV: string;

/**
 * Const
 */
const _URL_BASE_API_HISTORIAL_NOTIFICACIONES_W = URL_BASE_API_HISTORIAL_NOTIFICACIONES_W;
const _URL_BASE_API_REENVIO_NOTIFICACIONES_W = URL_BASE_API_REENVIO_NOTIFICACIONES_W;
const _URL_BASE_API_NOTIFICACIONES_W = URL_BASE_API_NOTIFICACIONES_W;
const _ENV = ENV;

/**
 * Export
 */
export {_URL_BASE_API_HISTORIAL_NOTIFICACIONES_W as URL_BASE_API_HISTORIAL_NOTIFICACIONES_W};
export {_URL_BASE_API_REENVIO_NOTIFICACIONES_W as URL_BASE_API_REENVIO_NOTIFICACIONES_W};
export {_URL_BASE_API_NOTIFICACIONES_W as URL_BASE_API_NOTIFICACIONES_W};
export {_ENV as ENV};